# Generated by Django 5.2.8 on 2025-12-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
